"""Render findings from persisted outputs; never estimates unfinished results."""
import json
from pathlib import Path
import pandas as pd
from data import ROOT
from run import ILLUSTRATION,PRICE_CONTROL
from formatting import prose_spacing


def pct(x):return f'{x:.2%}'
def money(x):return f'${x:,.0f}'

def render():
    r=ROOT/'results';m=pd.read_csv(r/'parameter_matrix.csv').set_index('id')
    v=m.loc[m.index.str.startswith('D_')];p=m.loc[m.index.str.startswith('P_')]
    a=json.loads((r/'accounting_audit.json').read_text());theta=json.loads((ROOT/'data/theta_comparison.json').read_text())
    d=m.loc[ILLUSTRATION];b=m.loc['benchmark_B'];slow=m.loc['slow']
    joint=((v.test_max_drawdown>=-.15)&(v.test_upside_capture>=.8)).sum()
    monthly_joint=((v.test_max_drawdown>=-.15)&(v.test_monthly_upside_capture>=.8)).sum()
    text=['# Test 1 findings — Partial Collar Protected Growth',
          '', '**Recommendation: FAIL the tested state-machine candidate against its combined protection/growth hypotheses; do not proceed automatically to Test 2.** This is a research disposition, not Principal acceptance or a verdict on every possible partial collar. Options economics are absent; no insurance-cost or guaranteed-loss claim.',
          '', '## Scope and evidence',
          '', 'Main simulation2005-06-10–2026-10-07; training ends2015-12-31, later observations held out chronologically.291 baseline runs:270 RVX-confirmed,18 price-only, slow-only, fully invested whole-share benchmarkA and passive300-share benchmarkB. Seven predeclared historical windows,55 matched assumption sensitivities,11 annual prior-only selections and one continuous walk-forward portfolio. No threshold was changed to favor performance; fixes before the final rerun enforced the predeclared opposite-transition cooldown and one-use Recovery1 semantics.',
          '', f'Theta terminal authentication succeeded. Accessible downloads contain{theta["iwm"]["matched_sessions"]:,} IWM closes2023-06-01 onward and{theta["rvx"]["matched_sessions"]:,} RVX closes2024-01-02 onward. Older stress-date requests returned403. IWM agrees with Yahoo within{theta["iwm"]["max_abs_close_difference"]:.7f} dollars; RVX agrees exactly with FRED on matched dates. The longer main dataset is explicitly Yahoo/FRED/Cboe, not ThetaData. Raw and normalized data are local. Hashes/validation/probes are persisted. Two missing RVX closes remain absent. Data vintages and historical publication latency remain limitations. See[DATA.md](DATA.md).',
          '', '## Fixed illustration and appropriate controls',
          '', 'The illustration was fixed before results:6% five-session price decline,50% five-session RVX expansion,50% price recovery and50% spike reversal. Initial300 shares cost$18,735 at the historical open, leaving about81% cash. That allocation, not just detection, is essential to interpreting low portfolio drawdown. Cash earns0% baseline; all comparators share execution and dividend assumptions.',
          '', '| Policy | CAGR | Max portfolio DD | Monthly upside capture | Ending NAV |',
          '|---|---:|---:|---:|---:|']
    for name,label in [('benchmark_A','A: fully invested IWM'),('benchmark_B','B: passive300 shares'),('slow','C: slow only'),(PRICE_CONTROL,'D: slow+price-only fast'),(ILLUSTRATION,'D: slow+RVX-confirmed fast')]:
        x=m.loc[name];text.append(f'|{label}|{pct(x.cagr)}|{pct(x.max_drawdown)}|{pct(x.monthly_upside_capture)}|{money(x.ending_value)}|')
    text += ['', f'The illustration ends{money(b.ending_value-d.ending_value)} below matched passive300-share ownership and{money(slow.ending_value-d.ending_value)} below slow-only. It records{int(d.tactical_exits)} exits/{int(d.tactical_reentries)} re-entries,{int(d.whipsaw_count)} opposite-sleeve reversals within20 sessions ({pct(d.whipsaw_frequency)} of tactical transactions),{pct(d.underinvested_fraction)} of sessions below300 shares, a longest underinvested spell of{int(d.longest_underinvested_sessions)} sessions, and{money(d.transaction_costs)} modeled transaction costs. All finish with300 shares; fixed100-share blocks cannot increase inventory beyond300. This test does not implement a capital-to-extra-share recycling policy.',
              '', 'Capture definition matters: the frozen matrix uses geometric **daily** up/down-session capture; monthly and arithmetic-daily versions are also exported. The illustration has daily upside capture'+pct(d.upside_capture)+', arithmetic-daily'+pct(d.arithmetic_upside_capture)+', monthly'+pct(d.monthly_upside_capture)+'. These are different statistics. Failure of the80% hypothesis persists with all three. Monthly capture is displayed in this report to make its conventional horizon explicit.',
              '', '## Chronology, plateau and walk-forward',
              '', f'Out of270 confirmed candidates, **{joint}** jointly satisfy held-out drawdown<=15% and daily upside capture>=80%; **{monthly_joint}** pass using monthly capture instead. None beats passive300-share ending NAV. Held-out confirmed-candidate median CAGR is{pct(v.test_cagr.median())}; drawdown range{pct(v.test_max_drawdown.min())} to{pct(v.test_max_drawdown.max())}; monthly upside capture range{pct(v.test_monthly_upside_capture.min())} to{pct(v.test_monthly_upside_capture.max())}. Neighbor joint-pass fractions are consequently0. This is a broad failure plateau on the combined target, not a sharp winning configuration. Some candidates meet the drawdown target; near15% is a preliminary hypothesis, not a certified capital floor.',
              '', 'Annual selection uses only pre-year target-distance and whipsaw scores, never maximum historical return. Separate yearly reset-account folds are not spliced into equity. The actual continuous walk-forward portfolio preserves cash/holdings and defers parameter adoption until both vetoes clear. It too fails the combined targets (see[walkforward_summary.csv](results/walkforward_summary.csv));2026 is a partial-year fold. All held-out data was available historically to this researcher, so this is pseudoholdout evidence, not prospective validation.',
              '', '## Stress findings',
              '', '| Historical window | Passive300 DD | Slow-only DD | Confirmed-fast DD | Confirmed-fast return |',
              '|---|---:|---:|---:|---:|']
    regimes=pd.read_csv(r/'regime_matrix.csv')
    for window in ['grinding_2008','crash_2020','v_recovery_2020','chop_2014_16','bull_2017','grinding_2022','bull_2023_24']:
        x=regimes[regimes.regime==window].set_index('id');y=x.loc[ILLUSTRATION]
        text.append(f'|{window}|{pct(x.loc["benchmark_B","max_drawdown"])}|{pct(x.loc["slow","max_drawdown"])}|{pct(y.max_drawdown)}|{pct(y.total_return)}|')
    events=pd.read_csv(r/'fast_event_diagnostics.csv');event=events[(events.id==ILLUSTRATION)&(events.signal_date=='2020-02-25')].iloc[0]
    text += ['', f'**Sudden crash:** February2020 activates fastA on{event.signal_date}, executes{event.execution_date}, before a slow restriction. Already-incurred five-session decline is{pct(event.signal_price5)}; next-open price is{pct(event.next_open_vs_precrash_raw_close)} below the precrash raw close. This is loss reduction after a trigger, not protection against the initial gap. The fast engine improves the2020 crash-window DD over slow-only but cannot guarantee<=15% in arbitrary paths; the synthetic gap test proves a counterexample.',
              '', '**V recovery:** confirmed-fast2020 recovery-window return is11.18%, versus11.85% passive300 and31.16% fully invested. Recovery avoids some downside but still misses upside; five-session velocity/RVX anchoring is not a free exit-and-re-entry advantage. No future bottom/peak is used. The strategy restores300 shares but does not generate extra shares.',
              '', '**Grinding bears:**2008 window improves matched passive DD, but gains little terminal-return advantage and incurs7 exits/7 restorations.2022 improves DD with five exits/four re-entries and remains underinvested for92.8% of sessions. A bounce aboveSMA50 does not establish secular recovery: Recovery1 may restoreB while still belowSMA200. Fresh rearmed bear conditions can recur; deterministic priority cannot make an inaccurate regime classification accurate.',
              '', '**Chop/bulls:**2014–16 confirmed-fast DD is worse than matched passive300 (8.41% versus8.01%) and return falls to3.42% versus6.22%.2017 creates no tactical transactions and stays at300 shares, yet cash drag remains.2023–24 adds four exits/four re-entries and trails passive3009.11% versus10.99%. Window returns are measured on continuing portfolios with different incoming NAV; identical share holdings can have different percentage returns because earlier damage changes the denominator. Do not interpret those as matched fresh-account alpha.',
              '', '## What RVX confirmation adds',
              '', 'Matched comparisons pair each of270 RVX configurations to its corresponding price threshold/recovery among18 price-only configurations (many-to-one; not270 independent controls). Held-out median CAGR difference is+0.124 percentage points; drawdown improvement median+0.045 percentage points, but the range includes material deterioration as well as improvement. Confirmation generally removes exits/whipsaws; it does not create the missing upside-capture plateau. Higher confirmation thresholds sometimes suppress crash detection entirely. Examine[volatility_paired.csv](results/volatility_paired.csv), rather than selecting the one best comparison.',
              '', '## Assumption and starting-allocation dependence',
              '', 'For the fixed illustration, removing all trading friction raises ending NAV only from$154,259 to$154,787, still below passive300.20bp adverse slippage lowers it to$152,750. Persistent-bear priority increases reversals27->38; one-block Recovery2 and dividend-payment delays do not change baseline outcomes because those rules do not bind materially here. Fast1/3-close confirmation changes results modestly. None establishes joint success.',
              '', 'Constant cash yield2%/4% materially changes results: CAGR3.24%/4.62%, DD9.85%/6.75%. Those are assumption sensitivities with equally remunerated comparators, not historical realized yields or tactical-engine profits. Long-term reserve return cannot be ignored.',
              '', 'After seeing the primary result, a **diagnostic**, non-selection starting-cohort check used regular five-year starts2005/2010/2015/2020/2025 for the fixed illustration and controls. Initial equity varies18.7%–66.9%; monthly upside capture25.4%–58.6%, all below80%.2020-start DD reaches18.38%. This shows substantial allocation/start dependence. The2005 conclusion cannot be transplanted to today\'s much larger300-share notional. These additional diagnostics do not authorize changing capital/sleeve sizing or selecting a favorable start.',
              '', '## Verification and unresolved boundaries',
              '', f'22 focused automated tests pass. Independent executed-trade replay passes across{a["runs"]} persisted runs,{a["sessions"]:,} daily states and{a["transactions"]:,} executed/denied transaction records; maximum NAV discrepancy{a["max_nav_rounding_error"]:.6f} dollars is CSV rounding. Runtime invariants prohibit negative cash, partial tactical blocks and core liquidation; no historical cash denial occurs, so denial behavior is established by targeted synthetic tests. Prefix perturbation verifies past indicators/states/trades do not change when future prices change. Synthetic tests are mechanics evidence, never historical performance.',
              '', 'Still unresolved: issuer-level historical distribution/payment-date audit, truly point-in-time vintage/timestamp validation, realistic historical cash yield, taxes, split-resizing policy beforeJune2005, and acceptance of provisional hysteresis/conflict rules. Core put/call economics, approval permissions, call-away restoration, call defense and1% insurance overhead all belong to later tests and remain unevaluated. No live execution is proposed.',
              '', '**Decision implication:** do not tune fast thresholds to rescue the observed deficit, and do not run a secondary slow-threshold optimization now. The supplied300-share policy fails to establish the intended growth/protection combination; allocation/cash treatment and restoration semantics need review at the policy level before more modeling. This does not authorize a replacement strategy or Test2.',
              '', '## Artifact links',
              '', '[Matrix](results/parameter_matrix.csv) · [Historical regimes](results/regime_matrix.csv) · [Sensitivities](results/sensitivities.csv) · [Neighbor robustness](results/neighbor_robustness.csv) · [Starting cohorts](results/start_date_diagnostics.csv) · [Accounting audit](results/accounting_audit.json) · [Frozen method](METHOD.md) · [Reproduction](README.md)',
              '', '![Equity, drawdown, exposure](results/equity_drawdown_exposure.png)',
              '', '![Sensitivity heatmaps](results/parameter_heatmaps.png)',
              '', '![Robustness distributions](results/robustness_distributions.png)',
              '', '![2020 states and holdings](results/state_timeline_2020.png)', '']
    (ROOT/'REPORT.md').write_text(prose_spacing('\n'.join(text)))

if __name__=='__main__':render()
