import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {spawn} from 'node:child_process';
import {readFile} from 'node:fs/promises';
import {parseArgs} from './wheelwright.mjs';
import {encodePathSymbol,decodePathSymbol,parseShowJson,validateShowObservation,presentShow,presentFields,readHeldQuote,showConfig,SHOW_FIELDS} from './ww-show.mjs';
import {showFieldManual} from './ww-show-fields.mjs';
import {capture,TOKEN,REQUEST_ID} from './ww-fetch-fixtures.mjs';
const cli=new URL('./wheelwright.mjs',import.meta.url).pathname,ww=new URL('./ww',import.meta.url).pathname,pty=new URL('./ww-acceptance-pty.py',import.meta.url).pathname;
const observation=(symbol='SPY')=>({observationId:'22222222-2222-4222-8222-222222222222',subject:{symbol,securityType:'ETF'},facts:{last:{price:671.23},bid:{price:671.2},ask:{price:671.25},reportedChangePercent:0.62},provenance:{provider:'tradier',environment:'PRODUCTION',acquisitionId:'33333333-3333-4333-8333-333333333333',authorityEpoch:'old',acquisitionPhase:'CLOSED',receivedAt:'2001-01-01T00:00:02.123456789123Z',committedAt:'2001-01-01T00:00:03Z'}});
const problem=(status,code)=>({type:`urn:wheelwright:problem:${code.toLowerCase()}`,title:({UNAUTHENTICATED:'Unauthenticated',FORBIDDEN:'Forbidden',NOT_FOUND:'Not found',INVALID_REQUEST:'Invalid request',INTERNAL_ERROR:'Internal error',CAPABILITY_UNAVAILABLE:'Capability unavailable'})[code],...(status===422?{invalidParams:[{name:'path.symbol',reason:'Invalid token.'}]}:{}),code,status,requestId:REQUEST_ID,detail:'No canonical direct quote is held.'});
async function fixture(work){const calls=[],state={responses:{},correlation:REQUEST_ID,media:undefined,wait:undefined};const server=createServer(async(req,res)=>{
 let body='';for await(const c of req)body+=c;assert.equal(req.method,'GET');assert.equal(body,'');assert.match(req.url,/^\/v2\/quotes\/[A-Z0-9_.-]+$/);assert.equal(req.headers.authorization,`Bearer ${TOKEN}`);
 const symbol=decodePathSymbol(req.url.split('/').at(-1));calls.push({symbol,path:req.url});if(state.wait)await state.wait(symbol);
 const entry=state.responses[symbol]??{status:200,body:observation(symbol)};res.statusCode=entry.status;res.setHeader('Content-Type',state.media??(entry.status===200?'application/json':'application/problem+json'));if(state.correlation)res.setHeader('X-Request-Id',state.correlation);if(entry.status===302)res.setHeader('Location','/forbidden');res.end(typeof entry.body==='string'?entry.body:JSON.stringify(entry.body));
 });server.listen(0,'127.0.0.1');await once(server,'listening');const env={WW_BASE_URL:`http://127.0.0.1:${server.address().port}`,WW_API_TOKEN:TOKEN,TZ:'America/Denver'};
 try{await work({calls,state,env,run:args=>capture([cli,'show',...args],env),terminal:async args=>JSON.parse((await capture([pty,ww,'show',...args],env,'python3')).stdout)});}finally{await new Promise(resolve=>{server.close(resolve);server.closeAllConnections();});}}
test('codec full alphabet properties, collisions and malformed rejection',()=>{const first='ABCDEFGHIJKLMNOPQRSTUVWXYZ^',tail=first+'0123456789./_-',seen=new Map();const check=s=>{const p=encodePathSymbol(s);assert.equal(decodePathSymbol(p),s);assert.equal(encodePathSymbol(decodePathSymbol(p)),p);if(seen.has(p))assert.equal(seen.get(p),s);seen.set(p,s);};for(const a of first){check(a);for(const b of tail){check(a+b);for(const c of tail)check(a+b+c);}}let seed=0x57575348;const next=()=>seed=(Math.imul(seed,1664525)+1013904223)>>>0;for(let k=0;k<10000;k++){let s=first[next()%first.length],n=1+next()%32;while(s.length<n)s+=tail[next()%tail.length];check(s);}assert.equal(encodePathSymbol('^'.repeat(32)).length,96);assert.equal(decodePathSymbol('BRK_5F2FB'),'BRK_2FB');for(const token of ['spy','BRK_','BRK_2','BRK_2fB','BRK_41','BRK_2E','BRK_25','SPY\n','BRK/B','^SPX','_5E'.repeat(33)])assert.throws(()=>decodePathSymbol(token));});
test('parser order, preflight conflicts, exact repeated ordered projection and no cap',()=>{for(const args of [['SPY','--quote'],['--quote','SPY'],['SPY'],['--jsonl','--verbose','SPY'],['--only','bid,ask','SPY']])assert.deepEqual(parseArgs(['show',...args]).symbols,['SPY']);assert.deepEqual(parseArgs(['show','spy','qqq','SPY']).symbols,['SPY','QQQ']);assert.deepEqual(parseArgs(['show','SPY','--only','bid,bid,ask']).only,['bid','bid','ask']);assert.equal(parseArgs(['show',...Array.from({length:40},(_,i)=>'S'+i)]).symbols.length,40);for(const args of [[],['SPY','--only',''],['SPY','--only','bid,'],['SPY','--only','bid, ask'],['SPY','--only','unknown'],['SPY','--only','bid','--only','ask'],['SPY','--only','bid','--verbose'],['SPY','--only','bid','--jsonl'],['SPY','bad symbol'],['SPY\n'],['--fields','SPY'],['SPY','--only=bid']])assert.throws(()=>parseArgs(['show',...args]),e=>e.code===2);});
test('registry, runtime catalog and generated semantic manual are the same vocabulary',async()=>{const rows=presentFields().trimEnd().split('\n');assert.deepEqual(rows.map(r=>r.split('\t')[0]),SHOW_FIELDS.map(f=>f.name));for(const f of SHOW_FIELDS){assert.ok(f.description.length>5);assert.ok(f.meaning.length>30);assert.ok(showFieldManual().includes(f.path));}const manual=await readFile(new URL('../docs/cli/ww-show-man.txt',import.meta.url),'utf8');assert.ok(manual.includes(showFieldManual()));assert.equal((await capture([new URL('./ww-show-man.mjs',import.meta.url).pathname,'--check'],{})).status,0);const local=await capture([cli,'show','--fields'],{WW_BASE_URL:'invalid',WW_API_TOKEN:'invalid token'});assert.equal(local.status,0);assert.equal(local.stdout,presentFields());assert.equal(local.stderr,'');assert.equal((await capture([cli,'show','--help'],{})).status,0);assert.equal((await capture([cli,'show','--man'],{})).stdout,manual);});
test('strict JSON types, full validation and exact machine numeric representation',()=>{const q=observation();q.facts.volume=123;let wire=JSON.stringify(q).replace('"volume":123','"volume":9007199254740993');const parsed=validateShowObservation(parseShowJson(wire),'SPY');assert.equal(presentShow(parsed,{only:['volume']}),'9007199254740993\n');assert.match(presentShow(parsed,{jsonl:true}),/"volume":9007199254740993/);for(const replacement of ['null','"1"','1.5','-1'])assert.throws(()=>validateShowObservation(parseShowJson(wire.replace('9007199254740993',replacement)),'SPY'));assert.throws(()=>parseShowJson('{"a":1,"a":2}'));assert.throws(()=>parseShowJson('{} {}'));q.facts.bid.sourceEventAt='asksize';assert.throws(()=>validateShowObservation(parseShowJson(JSON.stringify(q)),'SPY'));});
test('bare/quote equivalence, ordering, exact TSV/default human and complete JSONL',async()=>fixture(async({run,terminal,calls})=>{const bare=await run(['spy','QQQ','SPY']);assert.equal(bare.status,0);assert.equal(bare.stderr,'');assert.equal(bare.stdout,'SPY\tETF\t671.23\t0.62\t671.2\t671.25\t2001-01-01T00:00:02.123456789123Z\ttradier\tPRODUCTION\nQQQ\tETF\t671.23\t0.62\t671.2\t671.25\t2001-01-01T00:00:02.123456789123Z\ttradier\tPRODUCTION\n');assert.deepEqual(calls.map(c=>c.symbol),['SPY','QQQ']);assert.equal((await run(['--quote','SPY','QQQ'])).stdout,bare.stdout);assert.equal((await run(['SPY','QQQ','--only','bid,ask'])).stdout,'671.2\t671.25\n671.2\t671.25\n');assert.equal((await run(['--only','ask,symbol,bid','BRK/B','BRK_2FB','^SPX'])).stdout,'671.25\tBRK/B\t671.2\n671.25\tBRK_2FB\t671.2\n671.25\t^SPX\t671.2\n');const human=await terminal(['SPY','QQQ']);assert.equal(human.status,0);const lines=human.stdout.replace(/\x1b\[[0-9;]*m/g,'').split(/\r?\n/);assert.deepEqual(lines[0].trim().split(/\s{2,}/),['SYMBOL','TYPE','LAST','CHANGE %','BID','ASK','RECEIVED','PROVIDER','ENVIRONMENT']);assert.equal((human.stdout.match(/SYMBOL/g)??[]).length,1);assert.match(human.stdout,/\+0.62%/);assert.match(human.stdout,/Dec 31 17:00/);assert.deepEqual((await run(['--jsonl','SPY','QQQ'])).stdout.trim().split('\n').map(JSON.parse),[observation('SPY'),observation('QQQ')]);const verbose=await terminal(['SPY','QQQ','--verbose']);assert.match(verbose.stdout,/Subject SPY/);assert.match(verbose.stdout,/Subject QQQ/);assert.match(verbose.stdout,/2000-12-31 17:00:02.123456789123 -07:00/);const machineVerbose=await run(['SPY','--verbose']);assert.equal(machineVerbose.stdout.trimEnd().split('\t').length,SHOW_FIELDS.length-0); }));
test('missing versus zero, OTHER and unknown additions remain truthful',async()=>fixture(async({state,run,terminal})=>{const q=observation();q.subject.securityType='OTHER_UNDERLYING';delete q.facts.last;delete q.facts.ask;q.facts.bid.price=0;q.facts.open=1;q.facts.futureInternal='not public';state.responses.SPY={status:200,body:q};const r=await run(['SPY','--only','symbol,type,last,bid,ask']);assert.equal(r.stdout,'SPY\tOTHER\t\t0\t\n');const t=await terminal(['SPY','--only','last,bid,ask']);assert.match(t.stdout,/-\s+0\.00\s+-/);const json=await run(['SPY','--jsonl']);assert.ok(!json.stdout.includes('OTHER_UNDERLYING'));assert.ok(!json.stdout.includes('futureInternal'));assert.ok(!Object.hasOwn(JSON.parse(json.stdout).facts,'last'));}));
test('mixed success absence/corruption, all-failure, preflight and >30 subjects',async()=>fixture(async({state,run,calls})=>{state.responses.MISS={status:404,body:problem(404,'NOT_FOUND')};state.responses.BAD={status:500,body:problem(500,'INTERNAL_ERROR')};const result=await run(['SPY','MISS','BAD','QQQ','--only','symbol,bid']);assert.equal(result.status,1);assert.equal(result.stdout,'SPY\t671.2\nQQQ\t671.2\n');assert.match(result.stderr,/MISS:.*NOT_FOUND/);assert.match(result.stderr,/BAD:.*INTERNAL_ERROR/);assert.deepEqual(calls.map(c=>c.symbol),['SPY','MISS','BAD','QQQ']);const json=await run(['SPY','MISS','QQQ','--jsonl']);assert.equal(json.status,1);assert.equal(json.stdout.trim().split('\n').length,2);const failed=await run(['MISS','BAD']);assert.equal(failed.stdout,'');const before=calls.length;assert.equal((await run(['SPY','--only','bid','--jsonl'])).status,2);assert.equal(calls.length,before);const many=await run(Array.from({length:40},(_,i)=>'S'+i));assert.equal(many.status,0);assert.equal(many.stdout.trim().split('\n').length,40);}));
test('later failure does not suppress stdout already consumed',async()=>fixture(async({state,env})=>{let release;const consumed=new Promise(resolve=>release=resolve);state.wait=async symbol=>{if(symbol==='MISS')await consumed;};state.responses.MISS={status:404,body:problem(404,'NOT_FOUND')};const child=spawn(process.execPath,[cli,'show','SPY','MISS','--only','symbol,bid'],{env:{...process.env,...env}});let stdout='',stderr='';child.stdout.on('data',chunk=>{stdout+=chunk;assert.equal(stdout,'SPY\t671.2\n');release();});child.stderr.on('data',chunk=>stderr+=chunk);const [status]=await once(child,'close');assert.equal(status,1);assert.equal(stdout,'SPY\t671.2\n');assert.match(stderr,/MISS/);}));
test('complete response validation before only, response errors and secret suppression',async()=>fixture(async({state,run})=>{const q=observation();q.facts.bid.sourceEventAt='asksize';state.responses.SPY={status:200,body:q};let r=await run(['SPY','--only','last']);assert.equal(r.status,1);assert.equal(r.stdout,'');for(const body of ['{','{}',JSON.stringify(observation()).replace('671.23','"671.23"')]){state.responses.SPY={status:200,body};r=await run(['SPY']);assert.equal(r.status,1);assert.equal(r.stdout,'');}state.responses.SPY={status:200,body:observation()};state.correlation='bad';assert.equal((await run(['SPY'])).status,1);state.correlation=REQUEST_ID;state.media='text/html';assert.equal((await run(['SPY'])).status,1);state.media=undefined;for(const [status,code]of [[401,'UNAUTHENTICATED'],[403,'FORBIDDEN'],[422,'INVALID_REQUEST'],[503,'CAPABILITY_UNAVAILABLE']]){state.responses.SPY={status,body:problem(status,code)};assert.equal((await run(['SPY'])).status,1);}state.responses.SPY={status:404,body:{...problem(404,'NOT_FOUND'),detail:TOKEN}};r=await run(['SPY']);assert.ok(!r.stderr.includes(TOKEN));state.responses.SPY={status:302,body:problem(302,'NOT_FOUND')};assert.equal((await run(['SPY'])).status,1);}));
test('transport failure is safe and no redirect/retry/fallback; URL config preflight',async()=>{let calls=0;await assert.rejects(()=>readHeldQuote('SPY',showConfig(TOKEN,'http://127.0.0.1'),async(url,options)=>{calls++;assert.equal(url.pathname,'/v2/quotes/SPY');assert.equal(options.redirect,'error');assert.equal(options.body,undefined);throw Error(TOKEN);}),e=>!e.message.includes(TOKEN));assert.equal(calls,1);assert.throws(()=>showConfig(TOKEN,'http://example.com'),e=>e.code===2);});
test('shell composition and existing clean broken pipes',async()=>fixture(async({env})=>{const r=await capture(['-o','pipefail','-c',`${ww} show SPY QQQ --only symbol,bid | awk -F '\\t' '{print $1}'`],env,'bash');assert.equal(r.status,0);assert.equal(r.stdout,'SPY\nQQQ\n');const head=await capture(['-o','pipefail','-c',`${ww} show ${Array.from({length:100},(_,i)=>'S'+i).join(' ')} --jsonl | head -n 1`],env,'bash');assert.equal(head.status,0);assert.equal(head.stdout.trim().split('\n').length,1);}));

test('malformed Problem representations are operational failures without records',async()=>fixture(async({state,run})=>{for(const patch of [{type:'https://wrong.invalid'},{title:'wrong'},{detail:3},{invalidParams:null},{requestId:'wrong'}]){state.responses.SPY={status:404,body:{...problem(404,'NOT_FOUND'),...patch}};const r=await run(['SPY']);assert.equal(r.status,1);assert.equal(r.stdout,'');assert.match(r.stderr,/invalid Problem response/);}}));

test('public registry exactly matches frozen Product vocabulary and local DST clocks',async()=>{const contract=await readFile(new URL('../docs/contracts/api-v2-subject-show-held-quote.md',import.meta.url),'utf8');const inventory=contract.split('The bounded public vocabulary is:\n\n')[1].split('\n\n')[0].replace(/\s/g,'').split(',');assert.deepEqual(SHOW_FIELDS.map(f=>f.name),inventory);const q=validateShowObservation(parseShowJson(JSON.stringify(observation())),'SPY');const old=process.env.TZ;try{process.env.TZ='America/Denver';q.provenance.receivedAt='2026-03-08T08:59:59.123456789123Z';assert.match(presentShow(q,{tty:true,verbose:true}),/2026-03-08 01:59:59\.123456789123 -07:00/);q.provenance.receivedAt='2026-03-08T09:00:00Z';assert.match(presentShow(q,{tty:true,verbose:true}),/2026-03-08 03:00:00 -06:00/);}finally{if(old===undefined)delete process.env.TZ;else process.env.TZ=old;}});


test('output write failure is operational exit 1',async()=>fixture(async({env})=>{const hook='data:text/javascript,'+encodeURIComponent('process.stdout.write=()=>{const e=new Error("fixture output failure");e.code="ENOSPC";throw e;}');const r=await capture(['--import',hook,cli,'show','SPY'],env);assert.equal(r.status,1);assert.equal(r.stdout,'');assert.match(r.stderr,/SPY:.*fixture output failure/);}));
